################################################################################
# 06_check_crossrefs.R
#
# The main text refers to supplementary figures and tables by hard-coded number
# -- "Fig. S2", "Table S5" -- because \ref across two LaTeX documents does not
# resolve without the xr package, and a broken \ref compiles silently as "??".
#
# Hard-coded numbers rot the moment anything is inserted into the supplement.
# This checks them: it reads the order of \label{fig:...} and \label{tab:...} in
# supplementary.tex, works out what number each one will actually be given, and
# reports any main-text citation that points somewhere else.
#
#   Rscript R/06_check_crossrefs.R [manuscript.tex] [supplementary.tex]
#
# Defaults assume the text lives in ~/Desktop/6.Manuscript, which is outside
# this repository -- the prose is drafted in Overleaf.
################################################################################

# This script's own directory, however it was invoked.
PROJ <- local({
  a <- commandArgs(trailingOnly = FALSE)
  f <- sub("^--file=", "", a[grepl("^--file=", a)])
  if (length(f)) normalizePath(file.path(dirname(f), "..")) else normalizePath(".")
})

args <- commandArgs(trailingOnly = TRUE)
MS   <- if (length(args) >= 1) args[1] else "~/Desktop/6.Manuscript/main.tex"
SUPP <- if (length(args) >= 2) args[2] else "~/Desktop/6.Manuscript/supplementary.tex"
MS   <- path.expand(MS); SUPP <- path.expand(SUPP)

for (f in c(MS, SUPP)) {
  if (!file.exists(f)) stop("Not found: ", f,
                            "\n  Pass the paths as arguments if the text has moved.")
}

strip_comments <- function(x) sub("(?<!\\\\)%.*", "", x, perl = TRUE)

#' The supplement's float order, resolving \input{} so tables generated by
#' R/04_tables.R are counted where they are actually pulled in.
expand_inputs <- function(path) {
  lines <- strip_comments(readLines(path, warn = FALSE))
  out <- character(0)
  for (ln in lines) {
    m <- regmatches(ln, regexpr("\\\\input\\{[^}]+\\}", ln))
    if (length(m)) {
      tgt <- sub("^\\\\input\\{(.*)\\}$", "\\1", m[1])
      if (!grepl("\\.tex$", tgt)) tgt <- paste0(tgt, ".tex")
      # tables are staged next to the supplement by R/04_tables.R
      # Resolved against this script's own project, not the working directory:
      # the checker is useful precisely when it is run from somewhere else.
      cand <- c(file.path(dirname(path), tgt),
                file.path(PROJ, "overleaf", tgt),
                file.path(PROJ, "output", tgt))
      hit <- Filter(file.exists, cand)
      if (length(hit)) { out <- c(out, strip_comments(readLines(hit[1], warn = FALSE))); next }
      warning("Could not resolve \\input{", tgt, "} -- numbering may be wrong.",
              call. = FALSE)
      next
    }
    out <- c(out, ln)
  }
  out
}

supp <- expand_inputs(SUPP)

# Floats are numbered by the order their environments open, not by label order.
numbering <- function(lines, env, prefix) {
  n <- 0L; map <- character(0)
  for (ln in lines) {
    if (grepl(paste0("\\\\begin\\{", env, "\\}"), ln)) n <- n + 1L
    lab <- regmatches(ln, regexpr("\\\\label\\{[^}]+\\}", ln))
    if (length(lab) && n > 0L) {
      key <- sub("^\\\\label\\{(.*)\\}$", "\\1", lab[1])
      if (grepl(paste0("^", prefix), key)) map[key] <- paste0("S", n)
    }
  }
  map
}

fig_map <- numbering(supp, "figure", "fig:")
tab_map <- numbering(supp, "table",  "tab:")

cat("Supplementary figures:\n")
for (k in names(fig_map)) cat(sprintf("  %-22s %s\n", k, fig_map[[k]]))
cat("Supplementary tables:\n")
for (k in names(tab_map)) cat(sprintf("  %-22s %s\n", k, tab_map[[k]]))

## ---- what the main text claims ----------------------------------------------

ms <- paste(strip_comments(readLines(MS, warn = FALSE)), collapse = " ")

cited <- function(txt, word) {
  m <- gregexpr(paste0(word, "[~ ]*S([0-9]+)"), txt)
  unique(as.integer(sub(paste0(word, "[~ ]*S"), "",
                        regmatches(txt, m)[[1]])))
}

fig_cited <- sort(cited(ms, "Fig\\."))
tab_cited <- sort(cited(ms, "Table"))

# Section pointers ("Section S1.4", "(S1.8)") are the ones that rot most
# quietly: inserting a subsection renumbers everything after it and nothing
# complains. Numbering follows \section / \subsection order in the supplement.
# Numbers AND titles. A cited number that still exists is not the same as a
# cited number that still means what it did: inserting a subsection shifts every
# later one within a range that remains valid, so existence checks pass while
# every pointer silently moves. The titles are printed so that can be seen.
supp_titles <- local({
  sec <- 0L; sub <- 0L; out <- character(0)
  for (ln in supp) {
    m <- regmatches(ln, regexpr("^\\s*\\\\(sub)?section\\{.*\\}", ln))
    if (!length(m)) next
    title <- sub("^\\s*\\\\(sub)?section\\{(.*)\\}\\s*$", "\\2", m[1])
    if (grepl("^\\s*\\\\section\\{", ln)) {
      sec <- sec + 1L; sub <- 0L
      out[sprintf("S%d", sec)] <- title
    } else {
      sub <- sub + 1L
      out[sprintf("S%d.%d", sec, sub)] <- title
    }
  }
  out
})
supp_sections <- names(supp_titles)

sec_cited <- unique(unlist(regmatches(ms,
  gregexpr("S[0-9]+\\.[0-9]+", ms))))
sec_missing <- setdiff(sec_cited, supp_sections)

fig_have <- sort(as.integer(sub("^S", "", fig_map)))
tab_have <- sort(as.integer(sub("^S", "", tab_map)))

problems <- 0L
report <- function(kind, cited, have) {
  missing <- setdiff(cited, have)
  if (length(missing)) {
    cat(sprintf("\nPROBLEM: main text cites %s %s, which the supplement does not have.\n",
                kind, paste0("S", missing, collapse = ", ")))
    problems <<- problems + length(missing)
  }
  unused <- setdiff(have, cited)
  if (length(unused)) {
    cat(sprintf("\nNote: %s %s exist(s) but the main text never points at them.\n",
                kind, paste0("S", unused, collapse = ", ")))
  }
}

cat("\nMain text cites figures:", paste0("S", fig_cited, collapse = ", "),
    "\n               tables :", paste0("S", tab_cited, collapse = ", "), "\n")

report("figure", fig_cited, fig_have)
report("table",  tab_cited, tab_have)

cat("\nSupplement sections (check these read the way the main text describes\n",
    "them -- a number can survive an insertion while its meaning moves):\n", sep = "")
for (k in supp_sections) cat(sprintf("  %-7s %s\n", k, supp_titles[[k]]))
cat("\nMain text cites sections:", paste(sort(sec_cited), collapse = ", "), "\n")
if (length(sec_missing)) {
  cat(sprintf("\nPROBLEM: main text cites Section %s, which the supplement does not have.\n",
              paste(sec_missing, collapse = ", ")))
  problems <- problems + length(sec_missing)
}

if (problems) {
  cat(sprintf("\n%d dangling cross-reference(s).\n", problems))
  quit(status = 1)
}
cat("\nAll hard-coded supplementary cross-references resolve.\n")
